name: Test Python Generator

on:
  pull_request:
    paths:
      - 'seed/**'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4
        with:
          fetch-depth: '0'

      - name: Setup Python
        uses: actions/setup-python@f677139bbe7f9c59b41e40162b753c062f5d49a3 # v5
        with:
          python-version: '3.11'

      - name: Install requirements
        run: pip install -r seed/requirements.txt

      - name: Serialize seed
        run: python seed/serialize.py seed/seed.json

      - name: Generate testing_fieldtrials.json (HEAD)
        run: python3 seed/fieldtrials_testing_config_generator.py
          --use-current-branch
          --target-version 128.1.70.65
          --target-channel NIGHTLY
          --output fieldtrial_testing_config.json
          --output-revision brave-variations-revision.txt

      - name: Generate testing_fieldtrials.json (legacy seed.json)
        run: python3 seed/fieldtrials_testing_config_generator.py
          --target-date "2024-08-12 00:02:25 +0000"
          --target-version 128.1.70.65
          --target-channel NIGHTLY
          --output fieldtrial_testing_config.json
          --output-revision brave-variations-revision.txt

      - name: Generate testing_fieldtrials.json (production-archive)
        run: python3 seed/fieldtrials_testing_config_generator.py
          --target-date "2024-07-18 00:02:08 +0000"
          --target-version 127.1.70.1
          --target-channel NIGHTLY
          --output fieldtrial_testing_config.json
          --output-revision brave-variations-revision.txt

      - name: fmt seed
        run: |
          python3 ./.github/ci/griffin-study-utils.py fmt
          git diff --no-ext-diff --exit-code seed/seed.json
