name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: "0"

      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - run: |
          pip install -r seed/requirements.txt
          python seed/serialize.py seed/seed.json
