name: Test Perf Field Trials Generator

on:
  pull_request:
    paths:
      - 'seed/**'
      - 'studies/**'
      - 'src/**'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@eef61447b9ff4aafe5dcd4e0bbf5d482be7e7871 # v4
        with:
          fetch-depth: '0'

      - name: Setup Python
        uses: actions/setup-python@0b93645e9fea7318ecaed2b359559ac225c90a2b # v5
        with:
          python-version: '3.11'

      - name: Install requirements
        run: pip install -r seed/requirements.txt

      - name: Generate testing_fieldtrials.json (HEAD)
        run: python3 seed/fieldtrials_testing_config_generator.py
          --use-current-branch
          --target-version 128.1.70.65
          --target-channel NIGHTLY
          --output fieldtrial_testing_config.json
          --output-revision brave-variations-revision.txt

      - name: Generate testing_fieldtrials.json (legacy seed.json)
        run: python3 seed/fieldtrials_testing_config_generator.py
          --target-date "2024-08-12 00:02:25 +0000"
          --target-version 128.1.70.65
          --target-channel NIGHTLY
          --output fieldtrial_testing_config.json
          --output-revision brave-variations-revision.txt

      - name: Generate testing_fieldtrials.json (production-archive)
        run: python3 seed/fieldtrials_testing_config_generator.py
          --target-date "2024-07-18 00:02:08 +0000"
          --target-version 127.1.70.1
          --target-channel NIGHTLY
          --output fieldtrial_testing_config.json
          --output-revision brave-variations-revision.txt
