name: Test

on:
  push:
    branches: [main, production]
  pull_request:
    branches: [main, production]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3
        with:
          fetch-depth: '0'

      - name: Setup Python
        uses: actions/setup-python@65d7f2d534ac1bc67fcd62888c5f4f3d2cb2b236 # v4
        with:
          python-version: '3.11'

      - name: Install requirements
        run: pip install -r seed/requirements.txt

      - name: Serialize seed
        run: python seed/serialize.py seed/seed.json

      - name: fmt seed
        run: |
          python3 ./.github/ci/griffin-study-utils.py fmt
          git diff --no-ext-diff --exit-code seed/seed.json
