name: Test

on:
  push:
    branches: [main, production]
  pull_request:
    branches: [main, production]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: "0"

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install requirements
        run: pip install -r seed/requirements.txt

      - name: Serialize seed
        run: python seed/serialize.py seed/seed.json

      - name: fmt seed
        run: |
          python3 ./.github/ci/griffin-study-utils.py fmt
          git diff --no-ext-diff --exit-code seed/seed.json
